# Generated by Django 4.1.7 on 2023-11-18 17:57

import app.utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GallerySlider",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("1", "первый слайдер"),
                            ("2", "второй слайдер"),
                            ("3", "третий слайдер"),
                        ],
                        max_length=11,
                        unique=True,
                        verbose_name="название слайдера по позиции в макете",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайдер галереи",
                "verbose_name_plural": "Слайдер галереи",
            },
        ),
        migrations.CreateModel(
            name="GalleryImages",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="название для картинки",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="цена за которую был выполнен заказ",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("1", "первое маленькое изображение"),
                            ("2", "второе маленькое изображение"),
                            ("3", "большое снизу изображение"),
                            ("4", "большое справа изображение"),
                        ],
                        default="1",
                        max_length=11,
                        verbose_name="место на макете - слева направо",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=app.utils.models.image_gallery_path,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "slider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utils.galleryslider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображения к слайдерами",
                "verbose_name_plural": "Изображения к слайдерами",
            },
        ),
    ]
