# Generated by Django 4.1.7 on 2023-10-29 19:23

from django.db import migrations, models
import app.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0003_delete_userquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='название для картинки')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='цена за которую была выполнена')),
                ('type_place', models.CharField(choices=[('1', 'первое модальное'), ('2', 'второе модальное'), ('3', 'большое модальное'), ('4', 'боковое модальное')], default='1', max_length=11, verbose_name='место на макете')),
                ('image', models.ImageField(upload_to=app.utils.models.image_gallery_path, verbose_name='Изображение')),
            ],
        ),
    ]
