# Generated by Django 4.1.7 on 2023-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='type_place',
            field=models.CharField(choices=[('1', 'первое маленькое изображение'), ('2', 'первое маленькое изображение'), ('3', 'большое снизу изображение'), ('4', 'большое справа изображение')], default='1', max_length=11, verbose_name='место на макете'),
        ),
    ]
