# Generated by Django 4.1.7 on 2023-10-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_galleryimages_slider_alter_galleryimages_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryslider',
            name='name',
            field=models.CharField(choices=[('1', 'первый слайдер'), ('2', 'второй слайдер'), ('3', 'третий слайдер')], max_length=11, unique=True, verbose_name='название слайдера по позиции в макете'),
        ),
    ]
