# Generated by Django 4.1.7 on 2023-10-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_alter_galleryslider_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimages',
            options={'verbose_name': 'Изображения к слайдерами', 'verbose_name_plural': 'Изображения к слайдерами'},
        ),
        migrations.AlterModelOptions(
            name='galleryslider',
            options={'verbose_name': 'Слайдер галереи', 'verbose_name_plural': 'Слайдер галереи'},
        ),
    ]
