# Generated by Django 4.1.7 on 2024-01-15 20:00

import app.chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_ordermodel_user_account"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="offer",
            field=models.ForeignKey(
                default=app.chat.models.Conversation.get_proper_default,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="orders.orderoffer",
                verbose_name="оффер",
            ),
        ),
    ]
