# Generated by Django 4.1.7 on 2023-11-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemodel",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddField(
            model_name="messagemodel",
            name="to_chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatmodel",
                verbose_name="Чат",
            ),
        ),
        migrations.AddField(
            model_name="chatmodel",
            name="participants",
            field=models.ManyToManyField(
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники чата",
            ),
        ),
    ]
