# Generated by Django 4.1.7 on 2024-01-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_orderoffer_contactor_key"),
        ("chat", "0002_conversation_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="offer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat",
                to="orders.orderoffer",
                verbose_name="оффер",
            ),
        ),
    ]
