# Generated by Django 4.1.7 on 2024-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_conversation_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="hashcode",
            field=models.CharField(
                max_length=1000, null=True, unique=True, verbose_name="hascode"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(
                default=False, verbose_name="прочтено ли сообщение"
            ),
        ),
    ]
