# Generated by Django 4.1.7 on 2023-05-02 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_personalclientdata_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalclientdata',
            name='user_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
