# Generated by Django 4.1.7 on 2023-05-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_personalclientdata_user_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalclientdata',
            name='user_account_id',
        ),
    ]
