# Generated by Django 4.1.7 on 2023-05-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_useraccount_is_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
