# Generated by Django 4.1.7 on 2023-05-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_useraccount_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalClientData',
        ),
    ]
