# Generated by Django 4.1.7 on 2023-05-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='user_account_id',
        ),
    ]
