# Generated by Django 4.1.7 on 2023-05-04 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_remove_userfeedback_user_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='user_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
