# Generated by Django 4.1.7 on 2023-05-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_sellerdata_seller_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerdata',
            options={'verbose_name': 'Продавцы', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
