# Generated by Django 4.1.7 on 2023-06-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
