# Generated by Django 4.1.7 on 2023-07-03 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_cooperationoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperationoffer',
            old_name='user_account_id',
            new_name='user_account',
        ),
        migrations.RenameField(
            model_name='sellerdata',
            old_name='seller_type_activity',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='sellerdata',
            old_name='seller_name_company',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='sellerdata',
            old_name='seller_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='sellerdata',
            old_name='seller_activity',
            new_name='is_activ',
        ),
        migrations.RenameField(
            model_name='sellerdata',
            old_name='seller_telephone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='sellerdata',
            old_name='seller_requisites',
            new_name='requisites',
        ),
        migrations.RemoveField(
            model_name='sellerdata',
            name='user_account_id',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_partner',
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
