# Generated by Django 4.1.7 on 2023-07-15 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_rename_user_account_id_cooperationoffer_user_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'UserAccount', 'verbose_name_plural': 'UserAccount'},
        ),
    ]
