# Generated by Django 4.1.7 on 2023-07-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_alter_useraccount_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerData',
        ),
    ]
