# Generated by Django 4.1.7 on 2023-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_sellerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Почта на которую было отправлено письмо')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Время отправки запроса на сброс почты')),
            ],
        ),
    ]
