# Generated by Django 4.1.7 on 2023-08-06 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_alter_emailsendtime_options_emailsendtime_api_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон компании'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'the field must contain at least 5 characters')]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'the field must contain at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='person_telephone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(7, 'the field must contain at least 7 numbers')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'the field must contain at least 2 characters')]),
        ),
    ]
