# Generated by Django 4.1.7 on 2023-08-11 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0027_alter_sellerdata_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вопрос от пользователя')),
                ('admin_response', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ пользователю')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания обращения')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
