# Generated by Django 4.1.7 on 2023-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0028_contactsupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationoffer',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Запрос от пользователя'),
        ),
    ]
