# Generated by Django 4.1.7 on 2023-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0029_alter_cooperationoffer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsupport',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Проблема решена?'),
        ),
    ]
