# Generated by Django 4.1.7 on 2023-08-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0030_contactsupport_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('contractor', 'Исполнитель'), ('client', 'Заказчик')], default='client', max_length=11, verbose_name='Роль'),
        ),
    ]
