# Generated by Django 4.2.3 on 2023-09-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0032_userquota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquota',
            old_name='quota_cloud_size',
            new_name='total_cloud_size',
        ),
    ]
