# Generated by Django 4.1.7 on 2023-09-22 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0033_rename_quota_cloud_size_userquota_total_cloud_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='person_telephone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(7, 'the field must contain at least 7 numbers')], verbose_name='Номер телефона'),
        ),
    ]
