# Generated by Django 4.1.7 on 2023-10-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0035_alter_useraccount_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerData',
        ),
    ]
