# Generated by Django 4.1.7 on 2023-10-12 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0036_delete_sellerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен / Не активен')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Имя компании')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания аккаунта исполнителя')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='Телефон компании')),
                ('requisites', models.CharField(blank=True, max_length=100, verbose_name='Реквизиты компании')),
                ('activity_type', models.CharField(blank=True, max_length=100, verbose_name='Болванка тут должна быть связь с видом деятельности')),
            ],
            options={
                'verbose_name': 'Исполнители',
                'verbose_name_plural': 'Исполнители',
            },
        ),
    ]
