# Generated by Django 4.1.7 on 2023-10-17 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0037_contractordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'the field must contain at least 2 characters')]),
        ),
    ]
