# Generated by Django 4.1.7 on 2023-10-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_questionnairesection'),
        ('main_page', '0038_alter_useraccount_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractordata',
            name='card_permissions',
            field=models.ManyToManyField(blank=True, null=True, to='products.cardmodel'),
        ),
    ]
