# Generated by Django 4.1.7 on 2023-10-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0040_alter_contractordata_card_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractordata',
            name='activity_type',
        ),
    ]
