# Generated by Django 4.1.7 on 2023-10-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0042_alter_contactsupport_user_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperationoffer',
            name='user_account',
        ),
    ]
