# Generated by Django 4.1.7 on 2023-10-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0043_remove_cooperationoffer_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperationoffer',
            name='text',
        ),
    ]
