# Generated by Django 4.1.7 on 2023-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0044_remove_cooperationoffer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperationoffer',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя компании'),
        ),
        migrations.AddField(
            model_name='cooperationoffer',
            name='telephone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон'),
        ),
    ]
