# Generated by Django 4.1.7 on 2023-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0045_cooperationoffer_name_cooperationoffer_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperationoffer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя компании'),
        ),
        migrations.AlterField(
            model_name='cooperationoffer',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон'),
        ),
    ]
