# Generated by Django 4.1.7 on 2023-10-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0046_alter_cooperationoffer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsupport',
            options={'verbose_name': 'Обращения в поддержку', 'verbose_name_plural': 'Обращения в поддержку'},
        ),
        migrations.AlterModelOptions(
            name='cooperationoffer',
            options={'verbose_name': 'Предложения на сотрудничество', 'verbose_name_plural': 'Предложения на сотрудничество'},
        ),
    ]
