# Generated by Django 4.1.7 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_question",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Вопрос от пользователя",
                    ),
                ),
                (
                    "admin_response",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Ответ пользователю",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания обращения"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="Проблема решена?"),
                ),
            ],
            options={
                "verbose_name": "Обращения в поддержку",
                "verbose_name_plural": "Обращения в поддержку",
            },
        ),
    ]
