# Generated by Django 4.1.7 on 2023-11-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorAgreement",
            fields=[
                (
                    "user_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подписания соглашения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Соглашение с исполнителем",
                "verbose_name_plural": "Соглашения с исполнителями",
            },
        ),
    ]
