# Generated by Django 4.1.7 on 2024-02-15 20:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0003_alter_contractordata_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractordata",
            name="legal_address",
            field=models.CharField(
                default="Tyumen", max_length=128, verbose_name="Юридический адресс"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractordata",
            name="tin",
            field=models.CharField(default="0123456789", max_length=10, verbose_name="ИНН"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contractordata",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Телефон компании"
            ),
        ),
    ]
