# Generated by Django 4.1.7 on 2023-11-01 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Options",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Вопрос")),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            (1, "answer"),
                            (3, "sub_questions"),
                            (2, "text_field"),
                        ],
                        max_length=200,
                        verbose_name="Тип опции",
                    ),
                ),
                ("file_required", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionnaireCategory",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, verbose_name="тип - кухня, шкафы, кровати"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionnaireType",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "questionnaire_type",
                    models.CharField(
                        max_length=20,
                        null=True,
                        verbose_name="тип анкеты - короткая, длинная",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=300, null=True, verbose_name="описание анкеты"
                    ),
                ),
                (
                    "card_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.questionnairecategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionnaireChapter",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Раздел опросника"),
                ),
                (
                    "questionnaire_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.questionnairetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Вопрос")),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            (1, "text_field"),
                            (2, "choice_field"),
                            (3, "answer_not_required"),
                        ],
                        max_length=200,
                        verbose_name="Тип ответа",
                    ),
                ),
                ("file_required", models.BooleanField(default=False)),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_parrent",
                        to="questionnaire.options",
                    ),
                ),
                (
                    "questionnaire_chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.questionnairechapter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="options",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questionnaire.question"
            ),
        ),
    ]
