# Generated by Django 4.1.7 on 2023-11-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0002_alter_options_option_type_alter_question_answer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="options",
            name="option_type",
            field=models.CharField(
                choices=[("1", "answer"), ("3", "sub_questions"), ("2", "text_field")],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("2", "choice_field"),
                    ("1", "text_field"),
                    ("3", "answer_not_required"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
    ]
