# Generated by Django 4.1.7 on 2023-11-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0003_alter_options_option_type_alter_question_answer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="options",
            name="option_type",
            field=models.CharField(
                choices=[
                    ("text_field", "text_field"),
                    ("answer", "answer"),
                    ("sub_questions", "sub_questions"),
                ],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("answer_not_required", "answer_not_required"),
                    ("choice_field", "choice_field"),
                    ("text_field", "text_field"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
    ]
