# Generated by Django 4.1.7 on 2023-11-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0004_alter_options_option_type_alter_question_answer_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="options",
            options={
                "verbose_name": "Опция вопроса анкеты",
                "verbose_name_plural": "Опции вопроса анкеты",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "Вопрос анкеты",
                "verbose_name_plural": "Вопросы анкеты",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairecategory",
            options={
                "verbose_name": "Категория анкеты",
                "verbose_name_plural": "Категории анкеты",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairechapter",
            options={
                "verbose_name": "Раздел анкеты",
                "verbose_name_plural": "Разделы анкеты",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairetype",
            options={
                "verbose_name": "Тип анкеты",
                "verbose_name_plural": "Типы анкеты",
            },
        ),
        migrations.AlterField(
            model_name="options",
            name="option_type",
            field=models.CharField(
                choices=[
                    ("text_field", "text_field"),
                    ("sub_questions", "sub_questions"),
                    ("answer", "answer"),
                ],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("text_field", "text_field"),
                    ("answer_not_required", "answer_not_required"),
                    ("choice_field", "choice_field"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
    ]
