# Generated by Django 4.1.7 on 2023-11-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0005_alter_options_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="options",
            name="option_type",
            field=models.CharField(
                choices=[
                    ("answer", "answer"),
                    ("text_field", "text_field"),
                    ("sub_questions", "sub_questions"),
                ],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("choice_field", "choice_field"),
                    ("text_field", "text_field"),
                    ("answer_not_required", "answer_not_required"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
        migrations.AlterField(
            model_name="questionnairechapter",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Раздел опросника"),
        ),
    ]
