# Generated by Django 4.1.7 on 2023-11-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0028_alter_ordermodel_state"),
        ("products", "0067_remove_questionnairemodel_card_category_and_more"),
        (
            "questionnaire",
            "0006_alter_options_option_type_alter_question_answer_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionnairetype",
            old_name="card_category",
            new_name="questionnaire_category",
        ),
        migrations.RemoveField(
            model_name="questionnairecategory",
            name="name",
        ),
        migrations.AddField(
            model_name="questionnairecategory",
            name="card_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.cardmodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="options",
            name="option_type",
            field=models.CharField(
                choices=[
                    ("sub_questions", "sub_questions"),
                    ("text_field", "text_field"),
                    ("answer", "answer"),
                ],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("choice_field", "choice_field"),
                    ("answer_not_required", "answer_not_required"),
                    ("text_field", "text_field"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Ответ по заказу",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.ordermodel",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бланк ответов клиента",
                "verbose_name_plural": "Бланк ответов клиента",
            },
        ),
    ]
