# Generated by Django 4.1.7 on 2023-12-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="notifications",
            field=models.BooleanField(
                default=False, verbose_name="Отправка уведомлений"
            ),
        ),
    ]
