# Generated by Django 4.1.7 on 2023-12-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_useraccount_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="person_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания аккаунта"
            ),
        ),
    ]
