# Generated by Django 4.1.7 on 2024-01-02 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_useraccount_person_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailSendTime",
        ),
    ]
