# Generated by Django 4.1.7 on 2024-02-06 17:04

import random

from django.db import migrations


def migrate_avatar_for_user(apps, _):
    User = apps.get_model("users", "UserAccount")
    Avatar = apps.get_model("users", "UserAvatar")
    users = User.objects.all()
    for user in users:
        if not Avatar.objects.filter(user=user).exists():
            Avatar.objects.create(
                user=user, color="#%06x" % random.randint(0, 0xFFFFFF))


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_useravatar"),
    ]

    operations = [migrations.RunPython(migrate_avatar_for_user)]
