# Generated by Django 4.1.7 on 2024-02-06 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20240206_2004"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useragreement",
            options={
                "verbose_name": "Пользовательское соглашение",
                "verbose_name_plural": "Пользовательские соглашения",
            },
        ),
        migrations.AlterModelOptions(
            name="useravatar",
            options={
                "verbose_name": "Аватар пользователя",
                "verbose_name_plural": "Аватары пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="userquota",
            options={
                "verbose_name": "Квота пользователя",
                "verbose_name_plural": "Квоты пользователей",
            },
        ),
    ]
