# Generated by Django 4.1.7 on 2024-02-17 11:50

import app.users.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_useraccount_person_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="name",
            field=models.CharField(
                max_length=50, validators=[app.users.validators.NameFieldValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[app.users.validators.PasswordFieldValidator()],
                verbose_name="Пароль",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="person_telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+73452231231",
                max_length=128,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="surname",
            field=models.CharField(
                default="anonim",
                max_length=50,
                validators=[app.users.validators.NameFieldValidator(2)],
            ),
            preserve_default=False,
        ),
    ]
