# Generated by Django 4.2.2 on 2023-10-23 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmodel",
            options={"verbose_name": "Чат", "verbose_name_plural": "Чаты"},
        ),
        migrations.AlterModelOptions(
            name="messagemodel",
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.RemoveField(
            model_name="chatmodel",
            name="messages",
        ),
        migrations.RemoveField(
            model_name="messagemodel",
            name="body",
        ),
        migrations.AddField(
            model_name="messagemodel",
            name="text_content",
            field=models.TextField(default="default", verbose_name="Текст сообщения"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messagemodel",
            name="to_chat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatmodel",
                verbose_name="Чат",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatmodel",
            name="participants",
            field=models.ManyToManyField(
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники чата",
            ),
        ),
        migrations.AlterField(
            model_name="messagemodel",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="messagemodel",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Время отправки"
            ),
        ),
    ]
