# Generated by Django 4.1.7 on 2023-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="тип - кухня, шкафы, кровати",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип мебели на заказ - Category",
                "verbose_name_plural": "Тип мебели на заказ - Category",
            },
        ),
    ]
