# Generated by Django 4.1.7 on 2023-11-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ночной столик', 'bedside_table'), ('стол', 'table'), ('кухня', 'kitchen')], max_length=50, null=True, verbose_name='тип - кухня, шкафы, кровати'),
        ),
    ]
