# Generated by Django 4.1.7 on 2023-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('bedside_table', 'ночной столик'), ('table', 'стол'), ('kitchen', 'кухня')], max_length=50, null=True, verbose_name='тип - кухня, шкафы, кровати'),
        ),
    ]
