# Generated by Django 4.1.7 on 2023-12-11 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_active_alter_category_name"),
        ("products", "0005_alter_category_name"),
    ]

    operations = []
