# Generated by Django 4.1.7 on 2023-12-14 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_merge_20231214_1124"),
        ("products", "0006_merge_20231214_1150"),
        ("products", "0007_alter_category_name"),
    ]

    operations = []
