# Generated by Django 4.1.7 on 2023-12-14 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_merge_20231211_1752"),
        ("products", "0008_merge_20231214_1206"),
    ]

    operations = []
