version: '3.3'

# if port 5432 is in use check it:
# sudo lsof -i tcp:5432
# than kill process to start postgresql
#and then: kill -9 <process id> (macOS) or sudo kill <process id> (Linux).

#https://saasitive.com/tutorial/django-celery-redis-postgres-docker-compose/:
#to create new admin just do in command
#docker exec -it <container_id - app> python manage.py createsuperuser

#docker compose build app  -remake only app container after changes


services:

# Backend-project
  app:
    container_name: app-backend
    image: whywe/prod_image:latest
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "chmod +x /app/docker-entrypoint.sh && /app/docker-entrypoint.sh"
#    entrypoint:
#      [ "/app/docker-entrypoint.sh" ]
    volumes:
      - $FILE_PATH/static/:/app/static/
      - $FILE_PATH/media/:/app/media/
      - $FILE_PATH/files/:/app/files/
      - $FILE_PATH/media_type/:/app/media_type/
    environment:
      SECRET_KEY: $SECRET_KEY
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      EMAIL_PORT: $EMAIL_PORT
      EMAIL_USE_TLS: $EMAIL_USE_TLS
      TOKEN: $TOKEN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      CELERY_RESULT_BACKEND: $CELERY_RESULT_BACKEND
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      DJANGO_SUPERUSER_PASSWORD: $DJANGO_SUPERUSER_PASSWORD
      DJANGO_SUPERUSER_EMAIL: $DJANGO_SUPERUSER_EMAIL
      DJANGO_SUPERUSER_NAME: $DJANGO_SUPERUSER_NAME
      DJANGO_SUPERUSER_PERSON_TELEPHONE: $DJANGO_SUPERUSER_PERSON_TELEPHONE
      DJANGO_SUPERUSER_SURNAME: $DJANGO_SUPERUSER_SURNAME
    depends_on:
      - db
      - redis

  daphne:
    container_name: app-daphne-backend
    image: whywe/prod_image:latest
    restart: always
    ports:
      - "8001:8001"
    command: >
      sh -c "poetry run daphne -b 0.0.0.0 -p 8001 config.asgi:application"
    volumes:
      - $FILE_PATH/static/:/app/static/
      - $FILE_PATH/media/:/app/media/
      - $FILE_PATH/files/:/app/files/
      - $FILE_PATH/media_type/:/app/media_type/
    environment:
      SECRET_KEY: $SECRET_KEY
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      EMAIL_PORT: $EMAIL_PORT
      EMAIL_USE_TLS: $EMAIL_USE_TLS
      TOKEN: $TOKEN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      CELERY_RESULT_BACKEND: $CELERY_RESULT_BACKEND
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
    depends_on:
      - db
      - redis

# Postgres DB
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - $FILE_PATH/postgres_data/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

# Celery Worker
  worker:
    image: whywe/prod_image:latest
    restart: always
    command:
         sh -c "poetry run celery -A config.celery worker -l info --concurrency=1 --queues a,b"
    volumes:
      - $FILE_PATH/static/:/app/static/
      - $FILE_PATH/media/:/app/media/
      - $FILE_PATH/files/:/app/files/
      - $FILE_PATH/media_type/:/app/media_type/
    environment:
      SECRET_KEY: $SECRET_KEY
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      EMAIL_PORT: $EMAIL_PORT
      EMAIL_USE_TLS: $EMAIL_USE_TLS
      TOKEN: $TOKEN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      CELERY_RESULT_BACKEND: $CELERY_RESULT_BACKEND
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
    depends_on:
      - app
      - daphne



# Celery Beat Worker
  worker-beat:
    image: whywe/prod_image:latest
    restart: always
    command:
      sh -c "poetry run celery -A config beat -l info"
    volumes:
      - $FILE_PATH/static/:/app/static/
      - $FILE_PATH/media/:/app/media/
      - $FILE_PATH/files/:/app/files/
      - $FILE_PATH/media_type/:/app/media_type/
    environment:
      SECRET_KEY: $SECRET_KEY
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_HOST_USER: $EMAIL_HOST_USER
      EMAIL_HOST_PASSWORD: $EMAIL_HOST_PASSWORD
      EMAIL_PORT: $EMAIL_PORT
      EMAIL_USE_TLS: $EMAIL_USE_TLS
      TOKEN: $TOKEN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      CELERY_RESULT_BACKEND: $CELERY_RESULT_BACKEND
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
    depends_on:
      - worker


  redis:
    image: 'redis:7.2'
    expose:
      - 6379
    volumes:
      - redis-data:/data

  pgadmin:
    container_name: db_pg_admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - $FILE_PATH/static/:/var/html/static/
      - $FILE_PATH/media/:/var/html/media/
      - $FILE_PATH/files/:/var/html/files/
      - $FILE_PATH/media_type/:/var/html/media_type/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - $FILE_PATH/certbot/conf:/etc/letsencrypt
      - $FILE_PATH/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  redis-data:
