# Generated by Django 4.1.7 on 2023-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sending", "0002_alter_usernotifications_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotifications",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("None", "Уведомления отключены"),
                    ("email", "Уведомление по Email"),
                    ("tel", "Уведомление по номеру телефона"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
