# Generated by Django 4.1.7 on 2023-12-11 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sending", "0005_usernotifications_unique_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotifications",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("email", "Уведомление по Email"),
                    ("tel", "Уведомление по номеру телефона"),
                ],
                default="email",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usernotifications",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
