# Generated by Django 4.1.7 on 2023-11-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_category_name"),
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("answer_not_required", "answer_not_required"),
                    ("choice_field", "choice_field"),
                    ("text_field", "text_field"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
        migrations.AlterField(
            model_name="questionnairetype",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.category"
            ),
        ),
    ]
