# Generated by Django 4.1.7 on 2023-11-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0002_alter_question_answer_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="option_type",
            field=models.CharField(
                choices=[("sub_questions", "sub_questions"), ("answer", "answer")],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
    ]
