# Generated by Django 4.1.7 on 2023-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0004_alter_option_option_type_alter_question_answer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairetype",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активная анкета"),
        ),
        migrations.AlterField(
            model_name="option",
            name="option_type",
            field=models.CharField(
                choices=[("sub_questions", "sub_questions"), ("answer", "answer")],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
    ]
