# Generated by Django 4.1.7 on 2023-12-14 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0005_questionnairetype_active_alter_option_option_type"),
        ("questionnaire", "0007_alter_option_option_type"),
    ]

    operations = []
