# Generated by Django 4.1.7 on 2023-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_alter_option_option_type_alter_question_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairechapter',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция в анкете'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.CharField(choices=[('answer', 'answer'), ('sub_questions', 'sub_questions')], max_length=200, verbose_name='Тип опции'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text_field', 'text_field'), ('choice_field', 'choice_field'), ('answer_not_required', 'answer_not_required')], max_length=200, verbose_name='Тип ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция в анкете'),
        ),
    ]
