# Generated by Django 4.1.7 on 2023-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0008_questionnairechapter_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="option",
            name="option_type",
            field=models.CharField(
                choices=[("sub_questions", "sub_questions"), ("answer", "answer")],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("choice_field", "choice_field"),
                    ("text_field", "text_field"),
                    ("answer_not_required", "answer_not_required"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
    ]
