# Generated by Django 4.1.7 on 2023-12-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0008_merge_20231211_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("answer_not_required", "answer_not_required"),
                    ("choice_field", "choice_field"),
                    ("text_field", "text_field"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
    ]
