# Generated by Django 4.1.7 on 2023-11-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "questionnaire",
            "0009_question_answer_required_alter_option_option_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("choice_field", "choice_field"),
                    ("answer_not_required", "answer_not_required"),
                    ("text_field", "text_field"),
                ],
                max_length=200,
                verbose_name="Тип ответа",
            ),
        ),
    ]
