# Generated by Django 4.1.7 on 2023-12-14 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0008_merge_20231214_1124"),
        ("questionnaire", "0008_merge_20231214_1150"),
        ("questionnaire", "0010_alter_question_answer_type"),
    ]

    operations = []
