# Generated by Django 4.1.7 on 2024-01-09 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0015_alter_option_option_type_alter_question_answer_type"),
        ("questionnaire", "0016_alter_question_answer_type"),
    ]

    operations = []
