# Generated by Django 4.1.7 on 2024-01-13 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0017_merge_20240109_2051"),
        ("questionnaire", "0017_merge_20240112_2002"),
    ]

    operations = []
