# Generated by Django 4.1.7 on 2024-01-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0018_merge_20240113_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="option_type",
            field=models.CharField(
                choices=[("answer", "answer"), ("sub_questions", "sub_questions")],
                max_length=200,
                verbose_name="Тип опции",
            ),
        ),
        migrations.DeleteModel(
            name="QuestionnaireCategory",
        ),
    ]
