# Generated by Django 4.1.7 on 2023-11-18 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yandex_path",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Путь в облаке"
                    ),
                ),
                (
                    "server_path",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Путь на сервере"
                    ),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "yandex_size",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Размер файла в облаке"
                    ),
                ),
                (
                    "server_size",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Размер файла на сервере",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderFileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=250, verbose_name="Имя файла"),
                ),
                (
                    "yandex_path",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Путь в облаке"
                    ),
                ),
                (
                    "server_path",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Путь на сервере"
                    ),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "yandex_size",
                    models.IntegerField(verbose_name="Размер файла в облаке, б"),
                ),
                (
                    "server_size",
                    models.IntegerField(verbose_name="Размер файла на сервер, б"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "order_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания заказа"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Название заказа"
                    ),
                ),
                (
                    "order_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Описание заказа"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("offer", "Создание предложений"),
                            ("selected", "Исполнитель выбран"),
                            ("completed", "Заказ выполнен"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        null=True,
                        verbose_name="Куки-ключ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ клиента",
                "verbose_name_plural": "Заказ клиента",
            },
        ),
        migrations.CreateModel(
            name="OrderOffer",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "offer_create_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания офера"
                    ),
                ),
                (
                    "offer_price",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="Цена офера",
                    ),
                ),
                (
                    "offer_execution_time",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Время выполнения офера",
                    ),
                ),
                (
                    "offer_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Описание офера"
                    ),
                ),
                (
                    "offer_status",
                    models.BooleanField(
                        default=False, verbose_name="Принят офер или нет"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.ordermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Офер",
                "verbose_name_plural": "Офер",
            },
        ),
    ]
