# Generated by Django 4.1.7 on 2023-11-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questionnaire", "0003_alter_option_option_type"),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="questionnaire_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questionnaire.questionnairetype",
            ),
        ),
    ]
