# Generated by Django 4.1.7 on 2023-11-27 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_ordermodel_questionnaire_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="card_category",
        ),
    ]
