# Generated by Django 4.1.7 on 2023-12-16 18:13
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def fill_mymodel_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model('orders', 'OrderFileData')
    for obj in MyModel.objects.using(db_alias).all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_ordermodel_user_account"),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfiledata',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_mymodel_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='orderfiledata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False,
                                   editable=False, unique=True),
        ),
        migrations.RemoveField('OrderFileData', 'id'),
        migrations.RenameField(
            model_name='orderfiledata',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='orderfiledata',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4,
                                   serialize=False, editable=False),
        ),
    ]
