# Generated by Django 4.1.7 on 2024-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_alter_orderfiledata_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderfiledata",
            name="server_path",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Путь на сервере"
            ),
        ),
        migrations.AlterField(
            model_name="orderfiledata",
            name="server_size",
            field=models.PositiveIntegerField(
                blank=True, max_length=150, verbose_name="Размер файла на сервере"
            ),
        ),
        migrations.AlterField(
            model_name="orderfiledata",
            name="yandex_path",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Путь в облаке"
            ),
        ),
        migrations.AlterField(
            model_name="orderfiledata",
            name="yandex_size",
            field=models.PositiveIntegerField(
                blank=True, max_length=150, verbose_name="Размер файла в облаке"
            ),
        ),
    ]
