# Generated by Django 4.1.7 on 2024-01-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_orderfiledata_server_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderfiledata",
            name="server_size",
            field=models.PositiveIntegerField(
                blank=True, verbose_name="Размер файла на сервере"
            ),
        ),
        migrations.AlterField(
            model_name="orderfiledata",
            name="yandex_size",
            field=models.PositiveIntegerField(
                blank=True, verbose_name="Размер файла в облаке"
            ),
        ),
    ]
