# Generated by Django 4.1.7 on 2024-01-21 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_orderoffer_contactor_key"),
        ("orders", "0008_alter_orderfiledata_server_size_and_more"),
    ]

    operations = []
