# Generated by Django 4.1.7 on 2024-01-23 08:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_merge_20240121_2214"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorksheetFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=250, verbose_name="Имя файла"),
                ),
                (
                    "yandex_path",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Путь в облаке"
                    ),
                ),
                (
                    "server_path",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Путь на сервере"
                    ),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "yandex_size",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="Размер файла в облаке"
                    ),
                ),
                (
                    "server_size",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="Размер файла на сервере"
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.ordermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
