# Generated by Django 4.1.7 on 2024-01-31 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_remove_orderoffer_offer_status_orderoffer_status"),
        ("orders", "0010_worksheetfile"),
    ]

    operations = []
