# Generated by Django 4.1.7 on 2024-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_merge_20240131_2103"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderoffer",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderoffer",
            name="status",
            field=models.CharField(
                choices=[
                    ("processed", "В обработке"),
                    ("viewed", "Просмотрен"),
                    ("selected", "Выбран"),
                    ("rejected", "Отклонен"),
                ],
                default="processed",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
