# Generated by Django 4.1.7 on 2024-02-09 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_offerfile"),
        ("orders", "0012_orderoffer_is_archive_alter_orderoffer_status"),
    ]

    operations = []
