# Generated by Django 4.2.3 on 2023-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquota',
            name='quota_cloud_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='total_server_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
