# Generated by Django 4.2.3 on 2023-09-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_userquota_quota_cloud_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuota',
        ),
    ]
