# Generated by Django 4.1.7 on 2023-10-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_galleryimages_type_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimages',
            old_name='type_place',
            new_name='position',
        ),
    ]
