# Generated by Django 4.1.7 on 2023-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_rename_type_place_galleryimages_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySlider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('1', 'первый слайдер'), ('2', 'второй слайдер'), ('3', 'третий слайдер')], max_length=11, verbose_name='название слайдера по позиции в макете')),
            ],
        ),
    ]
