# Generated by Django 4.1.7 on 2023-10-30 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_galleryslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='slider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.galleryslider'),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='position',
            field=models.CharField(choices=[('1', 'первое маленькое изображение'), ('2', 'второе маленькое изображение'), ('3', 'большое снизу изображение'), ('4', 'большое справа изображение')], default='1', max_length=11, verbose_name='место на макете - слева направо'),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='цена за которую был выполнен заказ'),
        ),
    ]
