# Generated by Django 4.1.7 on 2024-02-12 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0013_merge_20240209_2143"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=250, verbose_name="Имя файла"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Путь в облаке"
                    ),
                ),
                (
                    "preview_path",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Путь на сервере"
                    ),
                ),
                (
                    "date_upload",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "yandex_size",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="Размер файла в облаке"
                    ),
                ),
                (
                    "server_size",
                    models.PositiveIntegerField(
                        blank=True, verbose_name="Размер файла на сервере"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл пользователя",
                "verbose_name_plural": "Файлы пользователей",
            },
        ),
        migrations.CreateModel(
            name="OfferFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="file.filemodel"
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderoffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл к офферу",
                "verbose_name_plural": "Файлы к офферам",
            },
        ),
    ]
