# Generated by Django 4.1.7 on 2024-02-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file", "0003_ipfilemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileToDelete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Путь до файла"
                    ),
                ),
                (
                    "preview_path",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Путь до превью файла"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл для удаления",
                "verbose_name_plural": "Файлы для удаления",
            },
        ),
    ]
