# Generated by Django 4.1.7 on 2023-05-20 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0024_alter_productimagemodel_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_time', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_description', models.CharField(blank=True, max_length=300, verbose_name='Описание заказа')),
                ('state', models.CharField(choices=[('auction', 'Аукцион'), ('new', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=15, verbose_name='Статус')),
                ('card_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.cardmodel')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ состоящий из продуктов',
                'verbose_name_plural': 'Заказ состоящий из продуктов',
            },
        ),
    ]
