# Generated by Django 4.1.7 on 2023-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderoffer_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_courier_service',
            field=models.CharField(blank=True, max_length=300, verbose_name='Цена доставки'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_deliver_price',
            field=models.CharField(blank=True, max_length=300, verbose_name='Цена доставки'),
        ),
    ]
