# Generated by Django 4.1.7 on 2023-06-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordermodel_order_courier_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Заказ клиента', 'verbose_name_plural': 'Заказ клиента'},
        ),
    ]
