# Generated by Django 4.1.7 on 2023-09-10 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_alter_orderoffer_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to=orders.models.nameFile)),
                ('image_name', models.CharField(blank=True, default='', max_length=40, verbose_name='название файла в системе и облаке')),
                ('date_upload', models.DateTimeField(auto_now=True, verbose_name='Дата создания изображения')),
                ('cloud_image_size', models.DateTimeField(auto_now=True, verbose_name='Облако - размер изображения')),
                ('preview_image_size', models.DateTimeField(auto_now=True, verbose_name='Сервер - размер изображения')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
