# Generated by Django 4.2.3 on 2023-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_imagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Название файла в системе и облаке'),
        ),
    ]
