# Generated by Django 4.1.7 on 2023-10-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_imagedata_image_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageData',
        ),
    ]
