# Generated by Django 4.1.7 on 2023-10-01 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_delete_imagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_path', models.CharField(blank=True, max_length=150, verbose_name='Путь в облаке')),
                ('server_path', models.CharField(blank=True, max_length=150, verbose_name='Путь на сервере')),
                ('date_upload', models.DateTimeField(auto_now=True, verbose_name='Дата создания записи')),
                ('yandex_size', models.CharField(blank=True, max_length=150, verbose_name='Размер файла в облаке')),
                ('server_size', models.CharField(blank=True, max_length=150, verbose_name='Размер файла на сервере')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel')),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
