# Generated by Django 4.1.7 on 2023-10-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_filedata_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderImageModel',
        ),
    ]
