# Generated by Django 4.1.7 on 2023-10-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_delete_orderimagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='order_id',
        ),
    ]
