# Generated by Django 4.1.7 on 2023-10-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_filedata_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='order_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='номер заказ, если есть'),
        ),
    ]
