# Generated by Django 4.1.7 on 2023-10-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_filedata_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='order_id',
        ),
    ]
