# Generated by Django 4.1.7 on 2023-10-10 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_delete_orderimagemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="order_courier_service",
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="order_deliver_price",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=150,
                verbose_name="Название заказа",
            ),
            preserve_default=False,
        ),
    ]
