# Generated by Django 4.1.7 on 2023-10-11 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0020_filedata_order_id"),
        ("orders", "0021_remove_ordermodel_order_courier_service_and_more"),
    ]

    operations = []
