# Generated by Django 4.1.7 on 2023-10-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0021_remove_ordermodel_order_courier_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Заказ создан"),
                    ("offer", "Создание предложений"),
                    ("review", "Рассмотрение предложений"),
                    ("selected", "Исполнитель выбран"),
                ],
                max_length=15,
                verbose_name="Статус",
            ),
        ),
    ]
