# Generated by Django 4.1.7 on 2023-10-11 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0065_questionnairesection"),
        ("orders", "0022_merge_20231011_0421"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="card_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.cardmodel",
            ),
        ),
    ]
