# Generated by Django 4.1.7 on 2023-10-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0040_alter_contractordata_card_permissions'),
        ('orders', '0023_alter_ordermodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='contractor_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.contractordata'),
        ),
    ]
