# Generated by Django 4.1.7 on 2023-10-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_ordermodel_contractor_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='state',
            field=models.CharField(choices=[('created', 'Заказ создан'), ('offer', 'Создание предложений'), ('auction', 'Заказ на аукционе'), ('auction_expired_no_offers', 'Аукцион завершен, предложений нет'), ('auction_expired', 'Аукцион завершен'), ('selected', 'Исполнитель выбран'), ('completed', 'Заказ выполнен')], max_length=50, verbose_name='Статус'),
        ),
    ]
