# Generated by Django 4.1.7 on 2023-10-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0027_alter_ordermodel_user_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("offer", "Создание предложений"),
                    ("selected", "Исполнитель выбран"),
                    ("completed", "Заказ выполнен"),
                ],
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
