# Generated by Django 4.1.7 on 2023-05-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('card_name', models.CharField(max_length=20, null=True, verbose_name='тип - кухня, гостиная')),
            ],
        ),
    ]
