# Generated by Django 4.1.7 on 2023-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=20, null=True, verbose_name='тип мебели - кровать, ящик... ')),
                ('user_account_id', models.ManyToManyField(null=True, to='products.cardmodel')),
            ],
        ),
    ]
