# Generated by Django 4.1.7 on 2023-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='user_account_id',
            field=models.ManyToManyField(to='products.cardmodel'),
        ),
    ]
