# Generated by Django 4.1.7 on 2023-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                choices=[('table', 'стол'), ('kitchen', 'кухня'), ('bedside_table', 'ночной столик')],
                max_length=50, null=True, verbose_name='тип - кухня, шкафы, кровати'),
        ),
    ]
