# Generated by Django 4.1.7 on 2023-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_card_name_cardmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='завершено ли создание предмета заказа?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.CharField(blank=True, max_length=350, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_size',
            field=models.CharField(blank=True, max_length=20, verbose_name='размеры высота x ширина x длина'),
        ),
    ]
