# Generated by Django 4.1.7 on 2023-05-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_cardmodel_options_alter_categorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_price',
            field=models.IntegerField(verbose_name='цена предмета'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_units',
            field=models.IntegerField(verbose_name='количество предметов в шт.'),
        ),
    ]
