# Generated by Django 4.1.7 on 2023-05-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_responsekitchenmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseKitchenModel',
        ),
    ]
