# Generated by Django 4.1.7 on 2023-05-25 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0033_questionsproductsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('response', models.CharField(blank=True, max_length=120, null=True, verbose_name='ответ по заказу')),
                ('position', models.CharField(blank=True, max_length=10, null=True, verbose_name='номер ответа по порядку')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.questionsproductsmodel')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бланк ответов клиента',
                'verbose_name_plural': 'Бланк ответов клиента',
            },
        ),
    ]
