# Generated by Django 4.1.7 on 2023-05-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_responsemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOptionsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('option', models.IntegerField(blank=True, null=True, verbose_name='опция выбора к вопросу')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.questionsproductsmodel')),
            ],
            options={
                'verbose_name': 'Опции для вопросов',
                'verbose_name_plural': 'Опции для вопросов',
            },
        ),
    ]
