# Generated by Django 4.1.7 on 2023-05-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_questionoptionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoptionsmodel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.categorymodel'),
            preserve_default=False,
        ),
    ]
