# Generated by Django 4.1.7 on 2023-05-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_questionoptionsmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoptionsmodel',
            name='option',
        ),
    ]
