# Generated by Django 4.1.7 on 2023-05-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_questionoptionsmodel_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoptionsmodel',
            name='category',
        ),
    ]
