# Generated by Django 4.1.7 on 2023-05-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_rename_questionoptionsmodel_questionoptionskitchenmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoptionskitchenmodel',
            options={'verbose_name': 'Опции - кухня', 'verbose_name_plural': 'Опции - кухня'},
        ),
    ]
