# Generated by Django 4.1.7 on 2023-05-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productmodel_product_units'),
        ('products', '0048_alter_questionoptionskitchenmodel_question_id'),
    ]

    operations = [
    ]
