# Generated by Django 4.1.7 on 2023-06-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_questionoptionsmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
