# Generated by Django 4.1.7 on 2023-06-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordermodel_order_courier_service_and_more'),
        ('products', '0051_delete_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel'),
            preserve_default=False,
        ),
    ]
