# Generated by Django 4.1.7 on 2023-06-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_ordermodel_options'),
        ('products', '0057_alter_responsemodel_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel'),
        ),
    ]
