# Generated by Django 4.1.7 on 2023-07-17 10:43

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_alter_responsemodel_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsproductsmodel',
            name='is_image',
            field=models.BooleanField(default=False, verbose_name='Изображение?'),
        ),
        migrations.CreateModel(
            name='ResponsesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.iamgeFile, verbose_name='Изображение')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.responsemodel')),
            ],
        ),
    ]
