# Generated by Django 4.1.7 on 2023-07-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_questionsproductsmodel_is_image_responsesimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
