# Generated by Django 4.1.7 on 2023-07-21 17:46

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_alter_responsesimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsesimage',
            name='image',
            field=models.ImageField(upload_to=products.models.iamgeFile, verbose_name='Изображение'),
        ),
    ]
