# Generated by Django 4.1.7 on 2023-10-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_alter_responsesimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('questionnaire_type', models.CharField(max_length=20, null=True, verbose_name='тип анкеты - короткая, длинная')),
                ('card_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cardmodel')),
            ],
            options={
                'verbose_name': 'Тип Анкеты',
                'verbose_name_plural': 'Тип Анкеты',
            },
        ),
    ]
