# Generated by Django 4.1.7 on 2023-10-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_questionnairemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairemodel',
            name='description',
            field=models.CharField(max_length=300, null=True, verbose_name='описание анкеты'),
        ),
    ]
