# Generated by Django 4.1.7 on 2023-10-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_questionnairemodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('section', models.CharField(max_length=20, null=True, verbose_name='Раздел анкеты с определенными вопросами')),
                ('questionnaire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.questionnairemodel')),
            ],
            options={
                'verbose_name': 'Разделы внутри анкеты',
                'verbose_name_plural': 'Разделы внутри анкеты',
            },
        ),
    ]
