# Generated by Django 4.1.7 on 2023-10-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_questionnairesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmodel',
            options={'verbose_name': 'Тип мебели на заказ - CardModel', 'verbose_name_plural': 'Тип мебели на заказ - CardModel'},
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='тип - кухня, шкафы, кровати'),
        ),
    ]
